name: FluentME CI/CD

on:
  push:
    branches: [ "main", "staging" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install
      run: npm install

    - name: Dar permissão ao Jest
      run: chmod +x ./node_modules/.bin/jest

    - name: Testes
      run: npm test

    - name: Build Docker
      run: docker build -t fluentme-api .

    - name: Deploy Staging
      if: github.ref == 'refs/heads/staging'
      run: echo "Deploy STAGING realizado"

    - name: Deploy Produção
      if: github.ref == 'refs/heads/main'
      run: echo "Deploy PRODUÇÃO realizado"